stages:
  - test
  - cleanup

before_script:
  - export ISOLATION=buildref${CI_BUILD_REF}$(echo ${CI_BUILD_REF_NAME}${TEST_URL} | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')
  - export COMPOSE_PROJECT_NAME=${ISOLATION}

test:
  stage: test
  script:
    - sed -i "s|http://www.example.com/|${TEST_URL}/|g" tests/acceptance.suite.yml
    - make up
    - sleep 5
    - make run-tests
  artifacts:
    paths:
      - tests/_output
    when: always

cleanup:
  stage: cleanup
  script:
    - make clean
  when: always