variables:
  COMPOSE_PROJECT_NAME: "buildpipeline${CI_PIPELINE_ID}${CI_BUILD_NAME}"

test:
  stage: test
  script:
    - sed -i "s|http://www.example.com/|${TEST_URL}/|g" tests/acceptance.suite.yml
    - make up
    - sleep 7
    - make run-tests
  artifacts:
    paths:
      - tests/_output
    when: always

after_script:
  - make clean
